image: alpine:latest

before_script:
  - apk add --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ zola

check:
  stage: test
  script:
    - zola check
  only:
    - merge_request

pages:
  stage: deploy
  script:
    - zola build
  artifacts:
    paths:
      - public
  only:
    - main
