header_left = [
    { title = "Blog", href = "/blog/" },
    { title = "FAQ", href = "/faq/" },
    { title = "Wiki", href = "https://wiki.flipdot.org/" },
    { title = "Kontakt", href = "/kontakt/" },
]

header_right = [
    { title = "RSS feed", href = "/rss.xml", icon_classes = "fas fa-rss" },
    { title = "Unser Chat-Raum", href = "https://matrix.to/#/#general:flipdot.org", icon_classes = "fas fa-hashtag" },
    { title = "flipdot im Fediverse", href = "https://social.flipdot.org/@flipdot", icon_classes = "fab fa-mastodon" },
    { title = "flipdot bei GitHub", href = "https://github.com/flipdot", icon_classes = "fab fa-github" },
    { title = "flipdot bei GitLab", href = "https://gitlab.com/flipdot", icon_classes = "fab fa-gitlab" },
    { title = "flipdot bei Vimeo", href = "https://vimeo.com/flipdot", icon_classes = "fab fa-vimeo-v" },
]

footer = [
    { title = "Login", href = "/admin/" },
    { title = "Impressum", href = "/impressum/" },
    { title = "Satzung", href = "/satzung/" },
]
