locale: 'de'

backend:
  name: gitlab
  repo: flipdot/nusite
  branch: main
  auth_type: pkce
  app_id: 46ca4cc2955a8aef10df8d37468d02411f0da9dfe64e78f58d77a2282059e934

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

site_url: https://nusite.flipdot.org

media_folder: "static/media" # Media files will be stored in the repo under images/uploads
public_folder: "/media"

collections:
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blogpost" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    format: toml-frontmatter
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Pfad", name: "path", widget: "string" }
      #- { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Inhalt", name: "body", widget: "markdown" }
  # Our pages e.g. About
  - name: "pages"
    label: "Seite"
    folder: "content/pages"
    format: toml-frontmatter
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Permalink", name: "path", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
  #- name: "projects"
  #  label: "Projekt"
  #  folder: "content/projekte"
  #  format: toml-frontmatter
  #  create: true
  #  nested:
  #    depth: 8
  #  meta:
  #    path: { label: "Pfad", index_file: "index", widget: "string" }
  #  slug: "{{slug}}"
  #  fields:
  #    - { label: "Titel", name: "title", widget: "string" }
  #    - { label: "Inhalt", name: "body", widget: "markdown" }
